"""Ajout champs nom, prenom, numero, entreprise à Avis

Revision ID: 07531669187d
Revises: d3194ac09928
Create Date: 2025-06-23 12:11:41.209440

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '07531669187d'
down_revision = 'd3194ac09928'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('avis', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nom', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('numero', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('entreprise', sa.String(length=100), nullable=True))
        batch_op.create_foreign_key(None, 'qr_code', ['qr_id'], ['id'])

    with op.batch_alter_table('reponse', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'question', ['question_id'], ['id'])
        batch_op.create_foreign_key(None, 'avis', ['avis_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reponse', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('avis', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('entreprise')
        batch_op.drop_column('numero')
        batch_op.drop_column('nom')

    # ### end Alembic commands ###
