"""Ajout champs nom, prenom, numero, entreprise à Avis

Revision ID: 5872aeca4ff1
Revises: 07531669187d
Create Date: 2025-06-23 13:33:50.297107

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5872aeca4ff1'
down_revision = '07531669187d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chambres',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nom', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('avis', schema=None) as batch_op:
        batch_op.add_column(sa.Column('chambre_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'qr_code', ['qr_id'], ['id'])
        batch_op.create_foreign_key(None, 'chambres', ['chambre_id'], ['id'])

    with op.batch_alter_table('reponse', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'avis', ['avis_id'], ['id'])
        batch_op.create_foreign_key(None, 'question', ['question_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reponse', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('avis', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('chambre_id')

    op.drop_table('chambres')
    # ### end Alembic commands ###
