"""Add texte_fr and texte_en to Question

Revision ID: 5889e2a6beb2
Revises: 9d57866ec84e
Create Date: 2025-06-27 15:28:07.994985

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5889e2a6beb2'
down_revision = '9d57866ec84e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('avis', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'chambres', ['chambre_id'], ['id'])
        batch_op.create_foreign_key(None, 'qr_code', ['qr_id'], ['id'])

    with op.batch_alter_table('question', schema=None) as batch_op:
        batch_op.add_column(sa.Column('texte_fr', sa.String(length=255), nullable=False))
        batch_op.add_column(sa.Column('texte_en', sa.String(length=255), nullable=True))
        batch_op.drop_column('texte')

    with op.batch_alter_table('reponse', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'avis', ['avis_id'], ['id'])
        batch_op.create_foreign_key(None, 'question', ['question_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reponse', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('question', schema=None) as batch_op:
        batch_op.add_column(sa.Column('texte', mysql.VARCHAR(length=255), nullable=False))
        batch_op.drop_column('texte_en')
        batch_op.drop_column('texte_fr')

    with op.batch_alter_table('avis', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')

    # ### end Alembic commands ###
