"""Ajout de champs à Livraison

Revision ID: 7fd625d03352
Revises: 72fa34dcc12f
Create Date: 2025-06-10 12:16:22.353739

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '7fd625d03352'
down_revision = '72fa34dcc12f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('avis', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'qr_code', ['qr_id'], ['id'])

    with op.batch_alter_table('qr_code', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date_creation', sa.DateTime(), nullable=True))
        batch_op.drop_column('chambre')

    with op.batch_alter_table('reponse', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'question', ['question_id'], ['id'])
        batch_op.create_foreign_key(None, 'avis', ['avis_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reponse', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('qr_code', schema=None) as batch_op:
        batch_op.add_column(sa.Column('chambre', mysql.VARCHAR(length=100), nullable=True))
        batch_op.drop_column('date_creation')

    with op.batch_alter_table('avis', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    # ### end Alembic commands ###
