"""Ajout du champ categorie à Question

Revision ID: 9e29c0c0c5cc
Revises: 6b9b5e76a58b
Create Date: 2025-06-04 11:51:16.929816

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '9e29c0c0c5cc'
down_revision = '6b9b5e76a58b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('avis', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'qr_code', ['qr_id'], ['id'])

    with op.batch_alter_table('question', schema=None) as batch_op:
        batch_op.alter_column('texte',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
        batch_op.alter_column('type',
               existing_type=mysql.VARCHAR(length=20),
               nullable=False)
        batch_op.alter_column('categorie',
               existing_type=mysql.VARCHAR(length=100),
               type_=sa.String(length=50),
               nullable=False)
        batch_op.drop_column('active')

    with op.batch_alter_table('reponse', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'avis', ['avis_id'], ['id'])
        batch_op.create_foreign_key(None, 'question', ['question_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reponse', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('question', schema=None) as batch_op:
        batch_op.add_column(sa.Column('active', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
        batch_op.alter_column('categorie',
               existing_type=sa.String(length=50),
               type_=mysql.VARCHAR(length=100),
               nullable=True)
        batch_op.alter_column('type',
               existing_type=mysql.VARCHAR(length=20),
               nullable=True)
        batch_op.alter_column('texte',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)

    with op.batch_alter_table('avis', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    # ### end Alembic commands ###
