"""Ajout de la colonne date_naissance à la table utilisateurs

Revision ID: b8c0ddb078f1
Revises: c872eea12097
Create Date: 2025-06-04 16:20:17.068327

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b8c0ddb078f1'
down_revision = 'c872eea12097'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('avis', schema=None) as batch_op:
        batch_op.alter_column('qr_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
        batch_op.create_foreign_key(None, 'qr_code', ['qr_id'], ['id'])

    with op.batch_alter_table('qr_code', schema=None) as batch_op:
        batch_op.alter_column('uuid',
               existing_type=mysql.VARCHAR(length=100),
               nullable=False)

    with op.batch_alter_table('reponse', schema=None) as batch_op:
        batch_op.alter_column('avis_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
        batch_op.alter_column('question_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
        batch_op.create_foreign_key(None, 'question', ['question_id'], ['id'])
        batch_op.create_foreign_key(None, 'avis', ['avis_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reponse', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('question_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
        batch_op.alter_column('avis_id',
               existing_type=mysql.INTEGER(),
               nullable=True)

    with op.batch_alter_table('qr_code', schema=None) as batch_op:
        batch_op.alter_column('uuid',
               existing_type=mysql.VARCHAR(length=100),
               nullable=True)

    with op.batch_alter_table('avis', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('qr_id',
               existing_type=mysql.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
