"""Ajout de la colonne date_naissance à la table utilisateurs

Revision ID: c872eea12097
Revises: d05babe0f316
Create Date: 2025-06-04 15:40:27.393325

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c872eea12097'
down_revision = 'd05babe0f316'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('avis', schema=None) as batch_op:
        batch_op.alter_column('qr_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
        batch_op.create_foreign_key(None, 'qr_code', ['qr_id'], ['id'])

    with op.batch_alter_table('reponse', schema=None) as batch_op:
        batch_op.alter_column('avis_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
        batch_op.alter_column('question_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
        batch_op.create_foreign_key(None, 'avis', ['avis_id'], ['id'])
        batch_op.create_foreign_key(None, 'question', ['question_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reponse', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('question_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
        batch_op.alter_column('avis_id',
               existing_type=mysql.INTEGER(),
               nullable=False)

    with op.batch_alter_table('avis', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('qr_id',
               existing_type=mysql.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
